name: Update docs

on:
  push:
    branches: [master]

jobs:
  update:
    if: "!contains(github.event.head_commit.message, 'docs: Update generated references')"
    runs-on: ubuntu-26.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_PULL_TOKEN }}
          extra_nix_config: |
            extra-substituters = https://nix-cache.nul.ie
            extra-trusted-public-keys = nix-cache.nul.ie-1:BzH5yMfF4HbzY1C977XzOxoPhEc9Zbu39ftPkUbH+m4=

      - name: Update assignment tables
        run: nix run .#update-docs-assignments

      - name: Update option reference
        run: nix run .#update-docs-options

      - name: Update DNS reference
        run: >
          nix run .#update-docs-dns --
          ams1.int.nul.ie
          100.10.in-addr.arpa
          2.d.4.0.0.c.7.9.e.0.a.2.ip6.arpa
          h.nul.ie
          168.192.in-addr.arpa
          0.d.4.0.0.c.7.9.e.0.a.2.ip6.arpa

      - name: Commit and push if changed
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          git remote set-url origin "${REPO_URL/https:\/\//https:\/\/oauth2:${GITEA_TOKEN}@}"
          git add docs/
          if ! git diff --cached --quiet; then
            git commit -m "docs: Update generated references"
            git push
          fi
